GET http://localhost:8080/commits?url=https://github.com/octocat/Hello-World.git&limit=1&offset=1
Accept: application/json

###

GET http://localhost:8080/commits?url=https://github.com/facebook/react-native.git&per_page=30&force_local=true


###

GET http://localhost:8080/commits?url=https://github.com/facebook/react-native.git&per_page=2&page=12&force_local=true


###

GET http://localhost:8080/commits?url=https://github.com/JackMind/codacy-commitviewer.git&per_page=3

###
GET http://localhost:8080/commits?url=https://github.com/JackMind/codacy-commitviewer.git&per_page=3&page=2

###

GET http://localhost:8080/commits?url=https://github.com/JackMind/codacy-commitviewer.git&per_page=3&force_local=true

###
GET http://localhost:8080/commits?url=https://github.com/JackMind/codacy-commitviewer.git&per_page=3&page=0&force_local=true
